name: object
description: "Simplify the process of converting Dart objects to JSON and vice versa, making it easier to work with JSON data in Dart applications."
version: 0.0.1
homepage: https://landamessenger.com
repository: https://github.com/landamessenger/object

environment:
  sdk: '>=3.2.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^6.2.0                              # android   ios   linux   macos   web   windows
  cloud_firestore: ^4.14.0                      # android   ios           macos   web
  intl: ^0.18.1                                 # android   ios   linux   macos   web   windows
  yaml: ^3.1.2                                  # android   ios   linux   macos   web   windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
